spring:
  profiles:
    include: db

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never

  mvc:
    path-match:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace